doctrine:
    dbal:
        driver: pdo_pgsql
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: 15.4
        options:
            !php/const PDO::MYSQL_ATTR_INIT_COMMAND: "SET group_concat_max_len = 999999999, NAMES 'utf8mb4'"

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Tab:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                is_bundle: false
                prefix: Tab\Domain\Model
