doctrine:
    dbal:
        driver: pdo_pgsql
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: 15.4
        use_savepoints: true


    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        enable_lazy_ghost_objects: true
        mappings:
            Polsl:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                is_bundle: false
                prefix: Polsl\Domain\Model
        controller_resolver:
            auto_mapping: false
