nelmio_api_doc:
    documentation:
        info:
            title: TAB Vending Machine Management app
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/(doc|doc.json)$) # Accepts routes under /api except /api/doc
