Tab\Application\Command\AddNewSnack\AddNewSnack:
  properties:
    name:
      - NotBlank:
          normalizer: trim
      - Length:
          max: 255
          normalizer: trim

Tab\Application\Command\UpdateSnack\UpdateSnack:
  properties:
    name:
      - NotBlank:
          normalizer: trim
      - Length:
          max: 255
          normalizer: trim

Tab\Application\Command\AddNewMachine\AddNewMachine:
  properties:
    location:
      - NotBlank:
          normalizer: trim
      - Length:
          max: !php/const Tab\Domain\Model\Machine\Location::MAX_LENGTH
          normalizer: trim
    positionsNumber:
      - NotBlank: ~
      - GreaterThanOrEqual: 0
    positionsCapacity:
      - NotBlank: ~
      - GreaterThanOrEqual: 0

Tab\Application\Command\UpdateMachine\UpdateMachine:
  properties:
    location:
      - NotBlank:
          normalizer: trim
          groups: ['changedLocation']
      - Length:
          max: !php/const Tab\Domain\Model\Machine\Location::MAX_LENGTH
          normalizer: trim
    positionsNumber:
      - GreaterThanOrEqual: 0
    positionsCapacity:
      - GreaterThanOrEqual: 0