Tab\Application\Command\AddNewSnack\AddNewSnack:
  properties:
    name:
      - NotBlank:
          normalizer: trim
      - Length:
          max: 255
          normalizer: trim

Tab\Application\Command\UpdateSnack\UpdateSnack:
  properties:
    name:
      - NotBlank:
          normalizer: trim
      - Length:
          max: 255
          normalizer: trim

Tab\Application\Command\AddNewMachine\AddNewMachine:
  properties:
    location:
      - NotBlank:
          normalizer: trim
      - Length:
          max: !php/const Tab\Domain\Model\Machine\Location::MAX_LENGTH
          normalizer: trim
    positionsNumber:
      - NotBlank: ~
      - GreaterThanOrEqual: 0
    positionsCapacity:
      - NotBlank: ~
      - GreaterThanOrEqual: 0

Tab\Application\Command\UpdateMachine\UpdateMachine:
  properties:
    location:
      - NotBlank:
          normalizer: trim
          groups: ['changedLocation']
      - Length:
          max: !php/const Tab\Domain\Model\Machine\Location::MAX_LENGTH
          normalizer: trim
    positionsNumber:
      - GreaterThanOrEqual: 0
    positionsCapacity:
      - GreaterThanOrEqual: 0

Tab\Application\Command\AddNewUser\AddNewUser:
  properties:
    email:
      - NotBlank:
          normalizer: trim
      - Length:
          max: !php/const Tab\Domain\Email::MAX_LENGTH
      - Email:
          mode: html5
      - Tab\Infrastructure\Symfony\Validator\Constraints\EmailExists: ~
    password:
      - NotBlank:
          normalizer: trim
      - Length:
          min: !php/const Tab\Domain\Model\User\Password::MIN_LENGTH
          max: !php/const Tab\Domain\Model\User\Password::MAX_LENGTH
    name:
      - NotBlank:
          normalizer: trim
      - Length:
          max: !php/const Tab\Domain\Model\User\Name::MAX_LENGTH
    surname:
      - NotBlank:
          normalizer: trim
      - Length:
          max: !php/const Tab\Domain\Model\User\Name::MAX_LENGTH
    roles:
      - NotBlank:
          normalizer: trim
      - All:
        - Choice:
            callback: [Tab\Domain\Model\User\Role, list]

Tab\Application\Command\AddNewMachineSnack\AddNewMachineSnack:
  constraints:
    - Tab\Infrastructure\Symfony\Validator\Constraints\MachinePositionTaken: ~
  properties:
    position:
      - NotBlank:
          normalizer: trim
      - Length:
          max: !php/const Tab\Domain\Model\Machine\SnackPosition::MAX_LENGTH
          normalizer: trim
    quantity:
      - NotBlank: ~
      - GreaterThan: 0

Tab\Application\Command\UpdateSnackPrice\UpdateSnackPrice:
  properties:
    price:
      - NotBlank: ~
      - GreaterThan: 0.0

Tab\Application\Command\UpdateUser\UpdateUser:
  properties:
    email:
      - NotBlank:
          normalizer: trim
          allowNull: true
      - Length:
          max: !php/const Tab\Domain\Email::MAX_LENGTH
      - Email:
          mode: html5
      - Tab\Infrastructure\Symfony\Validator\Constraints\EmailExists:
          groups: ['changedEmail']
    password:
      - NotBlank:
          normalizer: trim
          allowNull: true
      - Length:
          min: !php/const Tab\Domain\Model\User\Password::MIN_LENGTH
          max: !php/const Tab\Domain\Model\User\Password::MAX_LENGTH
    name:
      - NotBlank:
          normalizer: trim
          allowNull: true
      - Length:
          max: !php/const Tab\Domain\Model\User\Name::MAX_LENGTH
    surname:
      - NotBlank:
          normalizer: trim
          allowNull: true
      - Length:
          max: !php/const Tab\Domain\Model\User\Name::MAX_LENGTH
    roles:
      - NotBlank:
          normalizer: trim
          allowNull: true
      - All:
          - Choice:
              callback: [ Tab\Domain\Model\User\Role, list ]

Tab\Application\Command\BuySnack\BuySnack:
  properties:
    price:
      - NotBlank: ~
      - GreaterThan: 0.0