json-api.machines.list:
  path: 'machines'
  controller: 'Tab\UserInterface\Http\JsonApi\Machines\MachinesListAction'
  methods: GET

json-api.machines.create:
  path: 'machines'
  controller: 'Tab\UserInterface\Http\JsonApi\Machines\CreateNewMachineAction'
  methods: POST