json-api.snacks.list:
  path: 'snacks'
  controller: 'Tab\UserInterface\Http\JsonApi\Snacks\SnacksListAction'
  methods: GET

json-api.machines.list:
  path: 'machines'
  controller: 'Tab\UserInterface\Http\JsonApi\Machines\MachinesListAction'
  methods: GET

json-api.machines.create:
  path: 'machines'
  controller: 'Tab\UserInterface\Http\JsonApi\Machines\CreateNewMachineAction'
  methods: POST

json-api.machines.update:
  path: 'machines/{machineId}'
  controller: 'Tab\UserInterface\Http\JsonApi\Machines\UpdateMachineAction'
  methods: PATCH
  requirements:
    machineId: \d+

json-api.machines.remove:
  path: 'machines/{machineId}'
  controller: 'Tab\UserInterface\Http\JsonApi\Machines\RemoveMachineAction'
  methods: DELETE
  requirements:
    machineId: \d+

json-api.users.list:
  path: 'users'
  controller: 'Tab\UserInterface\Http\JsonApi\Users\UsersListAction'
  methods: GET