api:
    resource: './routing/api.yml'
    prefix: '/api/'
    defaults:
        _format: 'json'

json-api:
    resource: './routing/json-api.yml'
    prefix: '/api/json-api'
    defaults:
        _format: 'json'

api.test.login:
    path: 'test-login'
    controller: 'Tab\UserInterface\Http\Json\TestLoginAction'
    format: 'html'
    methods: GET