api:
    resource: './routing/api.yml'
    prefix: '/api/'
    defaults:
        _format: 'json'

json-api:
    resource: './routing/json-api.yml'
    prefix: '/api/json-api'
    defaults:
        _format: 'json'

report:
    resource: './routing/reports.yml'
    prefix: '/api/reports'
    defaults:
        _format: 'html'

api.test.login:
    path: 'test-login'
    controller: 'Tab\UserInterface\Http\Json\TestLoginAction'
    format: 'html'
    methods: GET

html.homepage.redirect:
    path: '/'
    controller: 'Tab\UserInterface\Http\Redirect\HomepageRedirectAction'
    format: 'html'
    methods: GET