parameters:
    database_host: postgres_test
    database_name: zwzt_test
    sodium_time_cost: !php/const '\Polsl\Packages\Constants\Hasher::TEST_SODIUM_TIME_COST'
    sodium_memory_cost_kilobytes: !php/const '\Polsl\Packages\Constants\Hasher::TEST_SODIUM_MEMORY_LIMIT_IN_KB'
    sodium_memory_cost_bytes: !php/const '\Polsl\Packages\Constants\Hasher::TEST_SODIUM_MEMORY_LIMIT_IN_BYTES'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Polsl\Packages\TestCase\:
        resource: '../packages/src/TestCase'
        exclude:
            - '../packages/src/TestCase/Client/SymfonyCrawler.php'
            - '../packages/src/TestCase/Fixtures/Entity/*'
            - '../packages/src/TestCase/Mother/Entity/*'
            - '../packages/src/TestCase/Validator/SymfonyViolationTest.php'
            - '../packages/src/TestCase/Validator/ViolationsTest.php'
        bind:
            $kernelBrowser: '@test.client'

    Polsl\Tests\TestCase\:
        resource: '../tests/TestCase/**/*'
        exclude: '../tests/TestCase/Application/{Service,Mock,Page,Mother,Client/JsonApi}/*'

    Doctrine\Common\DataFixtures\Executor\ORMExecutor:
        public: false
    Doctrine\Common\DataFixtures\Executor\AbstractExecutor:
        alias: 'Doctrine\Common\DataFixtures\Executor\ORMExecutor'
        public: false
    Doctrine\Common\DataFixtures\Purger\ORMPurger:
        public: false
    Doctrine\Common\DataFixtures\Purger\PurgerInterface:
        alias: 'Doctrine\Common\DataFixtures\Purger\ORMPurger'
        public: false
    Polsl\Domain\Service\ClockInterface: '@Polsl\Infrastructure\Php\PhpTimezoneAwareClock'
